/// The role of a chat message participant.
enum ButterChatRole {
  /// A message sent by the user.
  user,

  /// A message generated by the assistant/AI.
  assistant,

  /// A system-level message (not displayed in the UI by default).
  system,
}
